[
    {
        "number": "mnb-001",
        "name": "Captain America",
        "type": "Main Character",
        "baseAttack": 2,
        "baseDefense": 5,
        "health": 5,
        "level": 1,
        "teamAffiliation": "Avengers"
    },
    {
        "number": "mnb-002",
        "name": "Captain America",
        "type": "Main Character",
        "baseAttack": 5,
        "baseDefense": 7,
        "health": 5,
        "level": 2,
        "teamAffiliation": "Avengers"
    },
    {
        "number": "mnb-003",
        "name": "Hulk",
        "type": "Main Character",
        "baseAttack": 3,
        "baseDefense": 4,
        "health": 6,
        "level": 1,
        "teamAffiliation": "Avengers"
    },
    {
        "number": "mnb-004",
        "name": "Hulk",
        "type": "Main Character",
        "baseAttack": 6,
        "baseDefense": 6,
        "health": 6,
        "level": 2,
        "teamAffiliation": "Avengers"
    },
    {
        "number": "mnb-005",
        "name": "Iron Man",
        "type": "Main Character",
        "baseAttack": 2,
        "baseDefense": 4,
        "health": 5,
        "level": 1,
        "teamAffiliation": "Avengers",
        "flightSymbol": true,
        "rangeSymbol": true
    },
    {
        "number": "mnb-006",
        "name": "Iron Man",
        "type": "Main Character",
        "baseAttack": 3,
        "baseDefense": 7,
        "health": 5,
        "level": 2,
        "teamAffiliation": "Avengers",
        "flightSymbol": true,
        "rangeSymbol": true
    },
    {
        "number": "mnb-007",
        "name": "Spider-Man",
        "type": "Main Character",
        "baseAttack": 2,
        "baseDefense": 5,
        "health": 5,
        "level": 1,
        "teamAffiliation": "Avengers"
    },
    {
        "number": "mnb-008",
        "name": "Spider-Man",
        "type": "Main Character",
        "baseAttack": 4,
        "baseDefense": 8,
        "health": 5,
        "level": 2,
        "teamAffiliation": "Avengers"
    },
    {
        "number": "mnb-027",
        "name": "Storm",
        "type": "Main Character",
        "baseAttack": 2,
        "baseDefense": 5,
        "health": 5,
        "level": 1,
        "teamAffiliation": "X-Men",
        "flightSymbol": true
    },
    {
        "number": "mnb-028",
        "name": "Storm",
        "type": "Main Character",
        "baseAttack": 5,
        "baseDefense": 6,
        "health": 5,
        "level": 2,
        "teamAffiliation": "X-Men",
        "flightSymbol": true
    },
    {
        "number": "mnb-029",
        "name": "Wolverine",
        "type": "Main Character",
        "baseAttack": 3,
        "baseDefense": 4,
        "health": 5,
        "level": 1,
        "teamAffiliation": "X-Men"
    },
    {
        "number": "mnb-030",
        "name": "Wolverine",
        "type": "Main Character",
        "baseAttack": 8,
        "baseDefense": 4,
        "health": 5,
        "level": 2,
        "teamAffiliation": "X-Men"
    },
    {
        "number": "mnb-031",
        "name": "Deadpool",
        "type": "Main Character",
        "baseAttack": 2,
        "baseDefense": 4,
        "health": 6,
        "level": 1,
        "teamAffiliation": "X-Men",
        "rangeSymbol": true
    },
    {
        "number": "mnb-032",
        "name": "deadpool",
        "type": "Main Character",
        "baseAttack": 4,
        "baseDefense": 6,
        "health": 5,
        "level": 2,
        "teamAffiliation": "X-Men",
        "rangeSymbol": true
    },
    {
        "number": "mnb-033",
        "name": "Professor X",
        "type": "Main Character",
        "baseAttack": 2,
        "baseDefense": 4,
        "health": 5,
        "level": 1,
        "teamAffiliation": "X-Men"
    },
    {
        "number": "mnb-034",
        "name": "Professor X",
        "type": "Main Character",
        "baseAttack": 3,
        "baseDefense": 8,
        "health": 5,
        "level": 2,
        "teamAffiliation": "X-Men"
    },
    {
        "number": "mnb-053",
        "name": "Rocket",
        "type": "Main Character",
        "baseAttack": 2,
        "baseDefense": 4,
        "health": 5,
        "level": 1,
        "teamAffiliation": "Guardians",
        "rangeSymbol": true
    },
    {
        "number": "mnb-054",
        "name": "Rocket",
        "type": "Main Character",
        "baseAttack": 6,
        "baseDefense": 5,
        "health": 5,
        "level": 2,
        "teamAffiliation": "Guardians",
        "rangeSymbol": true
    },
    {
        "number": "mnb-055",
        "name": "Star-Lord",
        "type": "Main Character",
        "baseAttack": 2,
        "baseDefense": 5,
        "health": 5,
        "level": 1,
        "teamAffiliation": "Guardians",
        "rangeSymbol": true
    },
    {
        "number": "mnb-056",
        "name": "Star-Lord",
        "type": "Main Character",
        "baseAttack": 3,
        "baseDefense": 6,
        "health": 5,
        "level": 2,
        "teamAffiliation": "Guardians",
        "rangeSymbol": true
    },
    {
        "number": "mnb-057",
        "name": "Gamora",
        "type": "Main Character",
        "baseAttack": 2,
        "baseDefense": 5,
        "health": 5,
        "level": 1,
        "teamAffiliation": "Guardians"
    },
    {
        "number": "mnb-058",
        "name": "gamora",
        "type": "Main Character",
        "baseAttack": 7,
        "baseDefense": 5,
        "health": 5,
        "level": 2,
        "teamAffiliation": "Guardians"
    },
    {
        "number": "mnb-059",
        "name": "Groot",
        "type": "Main Character",
        "baseAttack": 1,
        "baseDefense": 1,
        "health": 6,
        "level": 1,
        "teamAffiliation": "Guardians"
    },
    {
        "number": "mnb-060",
        "name": "Groot",
        "type": "Main Character",
        "baseAttack": 7,
        "baseDefense": 7,
        "health": 6,
        "level": 2,
        "teamAffiliation": "Guardians"
    },
    {
        "number": "mnb-079",
        "name": "Green Goblin",
        "type": "Main Character",
        "baseAttack": 2,
        "baseDefense": 4,
        "health": 5,
        "level": 1,
        "teamAffiliation": "Villains United",
        "flightSymbol": true
    },
    {
        "number": "mnb-080",
        "name": "Green Goblin",
        "type": "Main Character",
        "baseAttack": 6,
        "baseDefense": 5,
        "health": 5,
        "level": 2,
        "teamAffiliation": "Villains United",
        "flightSymbol": true
    },
    {
        "number": "mnb-081",
        "name": "loki",
        "type": "Main Character",
        "baseAttack": 1,
        "baseDefense": 6,
        "health": 5,
        "level": 1,
        "teamAffiliation": "Villains United"
    },
    {
        "number": "mnb-082",
        "name": "Loki",
        "type": "Main Character",
        "baseAttack": 4,
        "baseDefense": 8,
        "health": 5,
        "level": 2,
        "teamAffiliation": "Villains United"
    },
    {
        "number": "mnb-083",
        "name": "Magneto",
        "type": "Main Character",
        "baseAttack": 2,
        "baseDefense": 4,
        "health": 5,
        "level": 1,
        "teamAffiliation": "Villains United",
        "flightSymbol": true,
        "rangeSymbol":true
    },
    {
        "number": "mnb-084",
        "name": "Magneto",
        "type": "Main Character",
        "baseAttack": 5,
        "baseDefense": 5,
        "health": 5,
        "level": 2,
        "teamAffiliation": "Villains United",
        "flightSymbol": true,
        "rangeSymbol": true
    },
    {
        "number": "mnb-085",
        "name": "Thanos",
        "type": "Main Character",
        "baseAttack": 3,
        "baseDefense": 4,
        "health": 6,
        "level": 1,
        "teamAffiliation": "Villains United"
    },
    {
        "number": "mnb-086",
        "name": "Thanos",
        "type": "Main Character",
        "baseAttack": 6,
        "baseDefense": 6,
        "health": 6,
        "level": 2,
        "teamAffiliation": "Villains United"
    }
}]