# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.box_check_update = true
  config.vm.network "private_network", ip: "192.168.100.100"
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
     sudo apt-get install -y nodejs
     sudo apt-get install -y build-essential
   SHELL
end
